apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: downscaler-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - scheduler.go
  resources:
  - downscalers
  verbs:
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: downscaler-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: downscaler-cluster-role
subjects:
  - kind: ServiceAccount
    name: downscaler-sa
    namespace: downscaler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: downscaler-sa
  namespace: downscaler
